### ISSUE TITLE
stress test research spike

### ISSUE THREAD

**Issue by braddmiller** [zcash/lightwalletd#179]
Conduct research spike to establish approach and LEO for stress testing lightwalletd per the requirements in #178

Time Box: 8 hours

**Comment by LarryRuane** [comment]
Results of this research spike:

# Lightwalletd startup
First, start a mainnet instance of `zcashd`. Then start lightwalletd with the following arguments:
```
go run cmd/server/main.go -conf-file ~/.zcash/zcash.conf -cache-size 400000
```
Alternatively, you can:
```
go build `cmd/server/main.go
./main -conf-file ~/.zcash/zcash.conf -cache-size 400000
```
You will now need to wait for the lightwalletd to download the blocks, while will take around 40 minutes. (After #186 is merged, this waiting will be a one-time event.)

# Load generation
We can use [`grpcurl`](https://github.com/fullstorydev/grpcurl) to submit the `GetBlockRange` RPC to create a significant and long-running load on the lightwalletd. The following command runs for around 10 seconds on my system (after the lightwalletd has run long enough to download all blocks since Sapling activation):
```
grpcurl -insecure -d '{"start":{"height":419200},"end":{"height":719199}}' localhost:9067 cash.z.wallet.sdk.rpc.CompactTxStreamer/GetBlockRange
```
You should see a stream of compact blocks appearing on standard output and no errors. (You can redirect stdout to a file or to `/dev/null`.)

To test many connections, we need to run many `grpcurl` simultaneous instances to the same lightwalletd, something like the following script:
```
#!/bin/bash
# Generate a gRPC load to a lightwalletd (which must be already running, mainnet)
iterations=${1-8} # default 8 iterations
seq $iterations | while read i
do
    time grpcurl -insecure -d '{"start":{"height":419200},"end":{"height":719199}}' localhost:9067 cash.z.wallet.sdk.rpc.CompactTxStreamer/GetBlockRange >/dev/null &
done
```
You can run the script with an argument for the number of copies of `grpcurl` to launch, default 8. This script will return almost immediately, but the `grpcurl` instances will be running asynchronously. You can see them using the `top` or `ps` commands. If you wish to interrupt the test, run `killall grpcurl`.

While this is running, monitor the network, memory, and CPU usage of the lightwalletd instance. We would like to discover how many simultaneous, active connections the lightwalletd can accommodate before running out of various resources, and also what level of services the clients receive. (We can measure the latter by timing the `grpcurl` instances.)

## resource limitations

It's very possible that the system will run out of resources before lightwalletd does. If you start (say) 1000 instances of `grpcurl`, you will likely see errors about not being able to `fork` processes.

To solve this, we need to run the `grpcurl` instances on one or more separate systems (cloud instances, probably) and point them all to the machine running lightwalletd.

## simultaneous instances multiple threads instead of multiple processes

We should write a simple gRPC client (in Go) that generates this load using multi-threading (i.e. using Go routines). This will use an order of magnitude fewer system resources than multiple instances of `grpcurl`. The level of programming effort should be about one day. This little test client should be committed to the lightwalletd repository.

# Further functional performance testing

The above is merely testing the efficiency of the gRPC mechanism, especially on the server side. Next, we should run tests such as fetching and sending transactions, and the other APIs, to ensure that these can be handled from multiple simultaneous clients.
