### ISSUE TITLE
Research Spike: darksidewalletd demo and Q&A

### ISSUE THREAD

**Issue by braddmiller** [zcash/lightwalletd#206]
Taylor is going to demo darksidewalletd for the team and answer questions, the outcome of this should be details on tickets related to testing reorgs in both wallets.

Time box: 6 hours

**Comment by lindanlee** [comment]
Taylor had this meeting on 3/12/2020. From slack, Taylor said: 

Summarizing the last meeting so that I remember on Monday (correct me if I'm wrong):

- Taylor working on getting the block heights in coinbase correct
- In parallel, Larry/Taylor pair on getting Kevin's requested range of blocks served by darksidewalletd
- Kevin tests that the wallet syncs (after a restore) against darksidewalletd
- Taylor fixes anything that's preventing that sync from working.
- Once that works, Larry adds an API for easily switching between the test cases, and Kevin/Pacu write the MVP test for the SDK using it
