### ISSUE TITLE
Reorg test data to remove a transaction

### ISSUE THREAD

**Issue by braddmiller** [zcash/lightwalletd#242]
Create a test data set for darksidewalletd that removes a transaction (at least one transaction back from the most recent received) related to the test wallets during a reorg.

**Comment by lindanlee** [comment]
This is not writing code, but generating data. 

One way to do this may to use the genblocks tool. Talk to @defuse if unclear on the details.

**Comment by defuse** [comment]
This should be pretty straightforward with `genblocks`, just move a transaction from one text file to another. Or we could grab mainnet blocks, but that's a little more tricky since you'll have to update the modified block's header (so that its hash changes) and then update `prevHash` field of all subsequent block headers.
