### ISSUE TITLE
Checkpointing support

### ISSUE THREAD

**Issue by lindanlee** [zcash/lightwalletd#304]
@LarryRuane 

Zcashd needs a new RPC to return the sapling tree. This should be an easy thing to move through zcashd since it's only informational and doesn't change the behavior of zcashd. 

Lightwalletd implements gRPC to call that zcashd RPC, get the data, and return it in as a grpc response. Wallets will not be sent this, but the wallets will manually pull this.

**Comment by gmale** [comment]
After more discussion and research, @LarryRuane was able to get this to work as a proof of concept.

What remains is to formalize it as an RPC on zcashd and then expose that call through lightwalletd. The lightwalletd call should accept a blockheight as input and return, at least the tree. We may want it to also return the block height, block hash, block time and network to match the [current checkpoints](https://github.com/zcash/zcash-android-wallet-sdk/blob/master/src/zcashmainnet/assets/zcash/saplingtree/930000.json).

Optionally, we might consider putting other features in to prevent abuse or misuse, like maybe
- rounding down to the nearest 5,000 block height
- only returning the sapling tree so that it's harder to use this gRPC call directly in apps
- returning JSON instead of gRPC so it's harder to use directly in apps
- only exposing it on the darksidewalletd so it's harder to use directly in apps

**Comment by LarryRuane** [comment]
See https://github.com/zcash/zcash/issues/4721. This ticket will cover the creation of the new gRPC.

**Comment by adityapk00** [comment]
The primary issue with checkpoints is that the user’s wallet needs to “trust” these checkpoints, so that a rougue lightwalletd can’t mislead it. If a checkpoint is fetched from lightwalletd, then it doesn't enhance the safety of the light client, since it still has to trust whatever lightwalletd is saying the sapling root is. 

On the other hand, an up-to-date checkpoint reduces the bootstrap time for new wallets, so it is very desirable.

So, my proposal is:
Fetch the latest sapling root, blockhash and blocknumber from the zcash p2p network

That is,
- The light client will connect to the zcash p2p network (on port 8233, just like a regular zcashd would)
- All this info is basically already available - We could just fetch the block header, which has all this info, so probably don’t need any changes in zcashd at all.

This approach has a lot of positive side effects:
- The lightclient will basically get the latest checkpoint to a block, so the wallet can get started only with 1 compactblock from lightwalletd.
- The lightclients can use the p2p network to broadcast transactions, plugging a huge privacy hole where today the lightwalletd learns a users outgoing txids
- We can also use the p2p network to fetch memos (via fetching the full blocks that have a users transactions), which plugs yet another privacy hole with lightwalletd.

The cons of this approach are:
- There is additional work to implementing this p2p network capability in librustzcash or in the lightclient SDK itself.
  - I think this shouldn’t be too complex, if we can find a way to share the code we build across all the lightclient developers.
- The p2p network is slower than lightwalletd.
  - However, this is somewhat mitigated, since the instances where we’ll use the p2p network, the user can afford a small delay. The main wallet’s operation will still be blazing fast.

Although it’s my own idea, I kinda love it because it kills many birds with one stone. This will be hugely privacy improving, and it will allow wallets to start faster.

I’m curious to see what people think.

**Comment by holmesworcester** [comment]
I like the general thrust of Aditya's proposal, because often we find ourselves wanting something between a light wallet and a full node. For us the main advantages of using a lightwallet in Zbay are:

* No huge disk space requirement
* No multi-hour initial sync
* Zcashd isn't stable enough to watch many addresses and run locally on a user's computer. It needs babysitting. Keeping it running properly on machines outside of our control has been a challenge. The lightwallet makes this somebody else's problem (thank you Aditya!)
* Easier-to-understand privacy properties when adding Tor to the mix, since a lightwalletd is more analogous to connecting to a website via Tor.

However the downsides are:

* Huge changes to privacy when receiving transactions
* Risk of lightwalletd downtime
* Centralization
* Increased latency for receiving messages, even once we have a 0-conf API.
* Actually an increase in CPU usage relative to full node when watching many addresses. I think this is because with a full node we could check some addresses more frequently than others, but the light client is checking all addresses each time (This is probably something that can be improved.)
* Trickiness when we have to rescan back in time before our initial checkpoint e.g. when we import a viewing key

If we had a full node that a) was stable b) could start with a "checkpoint" and c) didn't have a huge diskspace requirement, we'd use that. 

I don't know how helpful this is!

**Comment by holmesworcester** [comment]
My specific questions about Aditya's proposal are:

1. How do we verify that what we're getting from the p2p network is correct? 
2. What are the attacks that open up when we connect to the p2p network? It seems to raise the stakes.
3. Does connecting to the p2p network work in the mobile app context? (Curious)

My questions about the ECC proposal are:

1. Why not ship a checkpoint with the latest version of the app, and release often?
2. How does this change what a malicious lightwalletd can do to the user?

**Comment by gmale** [comment]
Just a quick response on this:
>Why not ship a checkpoint with the latest version of the app, and release often?

Good question and [that's exactly what we do](https://github.com/zcash/zcash-android-wallet-sdk/tree/master/src/zcashmainnet/assets/zcash/saplingtree) (with the minor nuance that we don't "release" externally. We release internally every 2 weeks.) Currently, producing checkpoints takes about 2-4 hours per sprint and this RPC will help reduce that down to milliseconds.

**Comment by gmale** [comment]
> How does this change what a malicious lightwalletd can do to the user?

I really like this question. As proposed, the RPC changes nothing because we intend to use it to simply create the files that we package with the app. This RPC also opens the door to doing that as part of a CI/CD process in the future. But this question really makes me think about a world with numerous lightwalletd servers. Could we improve privacy enough by simply connecting to multiple instances and using the consensus values? Then, for example, an attacker would have to take control of multiple servers just to send a malicious checkpoint and have it be accepted.

A malicious checkpoint can DoS a wallet--preventing it from being able to spend shielded sapling notes. So that's a critical risk to keep in mind with checkpoints.

> Does connecting to the p2p network work in the mobile app context?

Yes and no. From discussing this topic with Aditya yesterday, I understand that the p2p network uses a custom TCP protocol. I doubt a library exists that does this well on mobile but maybe we could, for instance, leverage some of the [rust code that Zebra uses](https://github.com/ZcashFoundation/zebra/tree/main/zebra-network) for this or maybe even port it. Henry mentioned that they created a [special method](https://doc.zebra.zfnd.org/zebra_network/fn.connect_isolated.html) for that use case.

> What are the attacks that open up when we connect to the p2p network? It seems to raise the stakes.

This is something I also want to explore and understand better because ligthwalletd, at least, uses TLS and certificate authorities so I have some level of trust that I'm connecting to the machine I expect. By definition, the p2p network is trustless so I wonder what attacks or privacy leaks would be enabled when going that route.

**Comment by defuse** [comment]
It would be really hard to get reliable information from the p2p network. There are several points of weakness:

1. Node discovery: how does the light client find out the IPs of some p2p network nodes, and what stops an attacker from hijacking this process so that the client always chooses their (malicious) node?
2. Plaintext, unauthenticated protocol: even assuming the client is connected to an honest p2p node, the protocol is in plaintext so their ISP or whoever else might be intercepting their traffic can modify the responses.

Light clients should validate information provided by lightwalletd using the proof of work -- given that there's enough proof of work on the block, assuming miners are honest, and given that all of the information is cryptographically tied to the block and its proof of work, then the information can be trusted.

**Comment by adityapk00** [comment]
>     1. Node discovery: 
I thought we could do exactly what the full node does - Start with a list of seed nodes, use the DNS lookup to get a list of IPs, and connect to a random one. Won't this have the same security properties as a full node?

> 2. Plaintext, unauthenticated protocol:
What's the difference between a light client doing this and a full node doing the same thing? Aren't the same issues present for the full node? 

The llight client, for purposes of connecting to the p2p network, will do exactly what a full node does - Since it is getting the full blocks, it can check the PoW and the header.

**Comment by defuse** [comment]
Yes, peer discovery is an issue for full nodes as well. If an attacker can intercept the DNS lookups then they can eclipse attack the node, nodes are particularly vulnerable when they first sync because of this. This is somewhat mitigiated by the fact zcashd remembers its peers' IPs and does not need to re-seed its peer list every time, but it's still an issue that we would not want to introduce into light clients unless we absolutely had to.

The protocol being plaintext and unauthenticated isn't an issue for full nodes because they have the full chain state and validate everything themselves. If the light client is going to start checking headers and PoW, there's no need to reach out to p2p nodes for the checkpoint data, they could just get it from lightwalletd and validate it the same way. That way there's no need to increase the attack surface by talking to p2p nodes.

Regarding the other proposed benefits of talking to p2p nodes:

> The lightclients can use the p2p network to broadcast transactions, plugging a huge privacy hole where today the lightwalletd learns a users outgoing txids

> We can also use the p2p network to fetch memos (via fetching the full blocks that have a users transactions), which plugs yet another privacy hole with lightwalletd.

This would stop lightwalletd from learning everyone's outgoing transactions and memo requests, but it actually makes the privacy problem much worse because every wallet's ISP will be able to see all of the transactions they're broadcasting and which memos they're fetching (all in plain text). Additionally, given the issues around peer seeding it may not end up helping at all, for example if wallets all end up connecting to a few nodes, or if an attacker can create hundreds of Sybil nodes and have most wallets connecting to them.

**Comment by adityapk00** [comment]
> because every wallet's ISP will be able to see all of the transactions they're broadcasting

Isn't this an issue for full nodes as well? The ISP learns all outgoing txns for full nodes. Does this imply using a lightclient today is more private than using a full node? (i.e., you trust the lightwalletd more than your ISP)

**Comment by adityapk00** [comment]
There's a lot of tradeoffs here that we'll need to think through. 

- Centralization of the lightwalletd vs the decentralized p2p network
- Should lightclients inherit the privacy properties of the full node zcashd? Does it need to be more private? Less private?
- Can we just encrypt traffic between nodes on the p2p network? (this is a zcashd change, though)
- If a lightclient can be eclipsed, the same arguments apply to lightwalletd as well - i.e., an attacker, instead of eclipsing a lightclient can simply eclipse a lightwalletd and achieve a much bigger attack. Shouldn't we make it harder for an attacker ?

**Comment by defuse** [comment]
> > because every wallet's ISP will be able to see all of the transactions they're broadcasting
> 
> Isn't this an issue for full nodes as well? The ISP learns all outgoing txns for full nodes. Does this imply using a lightclient today is more private than using a full node? (i.e., you trust the lightwalletd more than your ISP)

For outgoing transactions, yes. https://github.com/zcash/zips/pull/391 is some progress towards fixing that. For incoming transactions, no, because none of zcashd's network traffic reveals which transactions belong to it. An attacker watching the traffic just sees the zcashd receiving the *entire* blockchain, so they don't learn anything about which transactions belong to that node.

**Comment by LarryRuane** [comment]
Strictly on the topic of light clients trusting lightwalletd, there seems to be an assumption that their interaction has similar security requirements as P2P, and of course in P2P there's no trust (and shouldn't be). But can lightwalletd be more analogous to amazon.com? Could ECC or the foundation run an instance that has a registered TLS certificate? Yes, ECC or the foundation could be evil, just as amazon.com could be evil, but we trust amazon.com today, and doing so seems to work out okay.

**Comment by LarryRuane** [comment]
Strictly on the topic of light clients trusting lightwalletd, there seems to be an assumption that their interaction has similar security requirements as P2P, and of course in P2P there's no trust (and shouldn't be). But can lightwalletd be more analogous to amazon.com? Could ECC or the foundation run an instance that has a registered TLS certificate? Yes, ECC or the foundation could be evil, just as amazon.com could be evil, but we trust amazon.com, and doing so seems to work out okay.

It's true that an organization (like Ledger) may want to run their own instance so they don't have to trust ECC or ZF, and of course that should be possible. Can they create their own certificate (avoiding paying the expense of registering with a global CA) that their light clients use to verify that they're talking to the intended instance (not being eclipsed)? I don't have the technical knowledge to know, so that's a genuine question.

To state this differently, do we have to assume that light clients have no choice but to connect to lightwalletd instances that they cannot trust?

**Comment by defuse** [comment]
> There's a lot of tradeoffs here that we'll need to think through.
> 
>     * Centralization of the lightwalletd vs the decentralized p2p network

I'm not too concerned about this. In the long term, it would be best if the wallet did not need to trust lightwalletd at all for privacy or security, so that no risk would come from using centralized providers. What matters most in my opinion are the actual privacy and security properties we can achieve for the user. I would not support weakening any privacy properties in order to achieve a vaguely-defined notion of "decentralization".

>     * Should lightclients inherit the privacy properties of the full node zcashd? Does it need to be more private? Less private?

We should have the best privacy properties we can reasonably obtain! If we can avoid zcashd's flaws then we should.

>     * Can we just encrypt traffic between nodes on the p2p network? (this is a zcashd change, though)

This would be difficult. The problem is that encryption *requires* cryptographic authentication (otherwise an attacker can just pretend to be the node you're trying to connect to and see all the traffic). Maybe each node could have its own domain name with a Let's Encrypt certificate, but there's still the problem of Sybil attacks: an attacker could create 1,000 nodes so that wallets would likely connect to those nodes, so they can see the traffic even though it's encrypted and authenticated.

> 
>     * If a lightclient can be eclipsed, the same arguments apply to lightwalletd as well - i.e., an attacker, instead of eclipsing a lightclient can simply eclipse a lightwalletd and achieve a much bigger attack. Shouldn't we make it harder for an attacker ?

Yes, production lightwalletd operators should be monitoring it for signs of an eclipse attack (e.g. compare its latest block hash with the latest block hash obtained from various other instances of zcashd). Thanks for bringing that up, I'll make sure it's documented somewhere.

**Comment by defuse** [comment]
@LarryRuane Right now we're assuming lightwalletd is run by a trusted operator (like amazon.com). If the wallet connects to a malicious lightwalletd, the lightwalletd can do things like send their wallet fake transactions and monitor their activity. So at present nobody should be using a lightwalletd they don't trust.
