### ISSUE TITLE
FR: Allow `GetBlockRange` to stream blocks in descending order

### ISSUE THREAD

**Issue by adityapk00** [zcash/lightwalletd#350]
**What is your feature request?**
Right now, the `GetBlockRange` method streams blocks from lowest height to tallest height. For BlazeSync, it might be useful to have the blocks streamed backwards - i.e., tallest height to lowest height. Maybe have an optional parameter that specifies the direction in which to stream blocks

**How would this feature help you?**
Streaming blocks backwards allows wallets to detect incoming spends quicker, allowing users access to their most recent transactions first. 

cc: @LarryRuane , @braddmiller

**Comment by LarryRuane** [comment]
This should be easy, just generalize [`GetBlockRange()`](https://github.com/zcash/lightwalletd/blob/4e561f2cfd9bc78b7d930a2fe617f7d6335f5bf8/common/common.go#L407) to run the loop index either up or down. Rather than adding an optional parameter, it may make sense to just allow `start=20, end=10` to mean return 20, 19, ... 10. Currently, those arguments would return an empty list. This approach is _almost_ backward-compatible -- close enough, I think.

**Comment by adityapk00** [comment]
This is a great idea. We should just do this.

**Comment by braddmiller** [comment]
This looks like a really great solution, adding to our sprint

**Comment by braddmiller** [comment]
@mdr0id, can we get PR #355 up in our LWD instance for testing?
