### ISSUE TITLE
FR: Add new RPC to check if a nullifier has been spent

### ISSUE THREAD

**Issue by adityapk00** [zcash/lightwalletd#352]
**What is your feature request?**
Add a new RPC to `service.proto` that will allow Lightclients to check if a given sapling nullifier has been spent. The API will also accept a block range, that can narrow down the range of blocks to check for the nullifier. LightwalletD will return true/false and also the txid in which this nullifier was spent. 

Something like
```
// Check if a given nullifier was spent, and if it was, in what txid
rpc IsNullifierSpent(NullifierFilter) returns (NullifierTxID) {}

message NullifierFilter {
    bytes nf = 1;
    BlockRange range = 2;
}

message NullifierTxID {
    bool isSpent = 1;
    bytes txid = 2;
}
```

**How would this feature help you?**
Wallets that scan backwards (i.e., scan latest block first) have an interesting problem that they can't reliably detect spends. This is because a `CompactSpend` is just a nullifier, and the wallet doesn't yet know if this nullifier belongs to the wallet (Since it hasn't seen the `CompactOutput` that created this nullifier yet). 

If a wallet could detect if a nullifier was spent, and in which transaction, it can directly jump to the corresponding transaction and build the wallet state quicker. Also, if a nullifier has already been spent, the wallet doesn't need to update the note's witness, which makes scanning much faster.

**Comment by adityapk00** [comment]
cc: @gmale @LarryRuane @braddmiller 


This also probably changes the wallet threat model in ways that I don't understand (@defuse)

**Comment by gmale** [comment]
I, too, am curious of the impact on the threat model, as well as the additional trust we'd be placing in lightwalletd. Intuitively, it feels like this optimization might not be worth the privacy tradeoff.

Is there another way to achieve this? How big is the set of all unspent nullifiers?
If it's small enough, maybe we can download all unspent nullifiers since a given time. For instance:

- wallet scans from tip
- finds a tx from last thursday
- wallet downloads all unspent nullifiers since last thursday (checks if tx is spent)
- finds a tx from last monday
- wallet downloads all unspent nullifiers from monday to thursday
- etc.

**Comment by adityapk00** [comment]
One thing re threat model:

We can make it so that the wallet doesn't actually rely on this info, but only uses it as an optimization. The wallet could call this RPC, and then determine if the witnesses need to be updated. However, if the LightwalletD mislead the wallet, the wallet will detect it (the wallet eventually sees all nullifiers anyway), and just update the witnesses accordingly. The LightwalletD can slow down the sync by returning the wrong values for the RPC, but it can slow it down anyway just by adding a `sleep(2s)` in `GetBlockRange` 🤷

**Comment by defuse** [comment]
Technically, this won't actually change the user-facing threat model as-written, because the threat model says that lightwalletd and network eavesdroppers learn an approximation of the transaction graph. This API makes those attacks easier, but the threat model is already saying it's possible for attackers to do.

I'd really like to change fix these leaks in the future, though. Because this is another instance of the wallet directly telling lightwalletd which transactions belong to it (that it created, in this case), the only way to plug the information leak in the future would be to give up any performance gains we win by using this new API. 

I'm really weary of backing ourselves into a corner by making performance optimizations that come at a privacy cost, and then realizing that we can't fix the problems without sacrificing a ton of performance. We can kinda see that happening with the memo fetching leak, I recommend adding information leaks only if we're really really sure that we cant gain performance some other way, and that the performance gains are significant blockers to adoption.

**Comment by defuse** [comment]
Technical details about the attacks:  Currently, to construct a wallet's transaction graph, lightwalletd has to remember all of its outgoing transactions at the time they're spent (associating them to the wallet's IP address), and then combine that with all of the wallet's memo fetches (which tell lightwalletd which were sent *to* the wallet). When this API is in use, the attack is much easier: when a wallet imports from a seed, it's going to tell lightwalletd which transactions went to it through the memo fetches *and also* which transactions went outbound through the nullifier lookups. So, it makes the attack easier by removing the lightwalletd attacker's need to have compromised lightwalletd at the time transactions were sent, and to remember them.

**Comment by adityapk00** [comment]
I've changed my mind about this API. I think the client should detect this on the client side, by watching the nullifiers that were spent. There's only ~500k nullifiers total since sapling genesis, so it's not that many nullifiers to keep track of.

**Comment by geffenz** [comment]
Closing since requester changed their mind AND this would require zcashd and lightwalletd changes.
