### ISSUE TITLE
Breaking API change

### ISSUE THREAD

**Issue by hhanh00** [zcash/lightwalletd#396]
**What is the bug?**
TreeState used to have a `tree` field in V4. 
In V5, it has `saplingTree` and `orchardTree` but `tree`.

I appreciate the new API providing both sapling and orchard commitment tree states.
The issue is that with a lack of backward compatibility and versioning, old clients will fail when they connect to a newer server.

I suggest you do not change the existing API and introduce new methods for Orchard.

Thanks,
--h

**Comment by str4d** [comment]
This is not a breaking change. gRPC uses protobuf, which is designed to precisely enable these kinds of changes, because fields are not referenced by name, but by index. Specifically, the `saplingTree` field uses the same field index as the previous `tree` field, so the two names are equivalent.

If what you are referring to is the fact that us renaming the field in the protobuf definition in this repository causes _locally generated APIs_ to be renamed, then the solution is to rename that field back to `tree` in your local copy of the protobuf file.

**Comment by hhanh00** [comment]
Sounds good. Thanks!
