### ISSUE TITLE
Migrate .gitlab-ci.yml to Github Actions

### ISSUE THREAD

**Issue by yasserisa** [zcash/lightwalletd#474]

**Comment by LarryRuane** [comment]
Is this something I can help out with? I don't really understand CI. But if you'd like, I can figure this out completely (rather than taking up any more of your time), it would be a good learning experience. I'm sure it's probably pretty easy.

I do know that for a long time, submitting a PR using my fork doesn't run CI (it reports that it's waiting but it never runs), and it would be great to have that fixed. If I recall correctly, if I create a branch of `zcash/lightwalletd` (instead of using my fork) as the PR branch, it runs CI. But I haven't done that in a long time; I think it's better GitHub hygiene to use our own forks, as is done on other repos. So instead, I've just been using my admin privileges to force the merge (I first run the test suite myself manually).

I think the only thing CI would have to do is to run that test suite:
```
$ go test ./...
```
It might also be nice to verify that the [Go formatter](https://go.dev/blog/gofmt) doesn't find anything to do (that is, it's already formatted correctly). That happens automatically with the tools I use (vscode), but might be nice if other people's PRs don't do that. I could figure out how to do that (also will be pretty easy).

**Comment by yasserisa** [comment]
The currently configured CI is in gitlab-ci. Every time a PR is made, it sends a webhook to Gitlab-CI and runs the instructions from the .gitlab-ci.yaml file. My intention is to migrate that file, which is not complicated, and we can add more things like unit tests, lint checking, SAST, etc.

If you'd like, we can do it together. I could start with the base to give you a guide, and the rest is almost copy, paste, and add the necessary commands. We can coordinate via Slack if you prefer.

**Comment by LarryRuane** [comment]
Perfect, Yasser, let's try that way, thanks!

**Comment by yasserisa** [comment]
> Perfect, Yasser, let's try that way, thanks!

Here is the base: https://github.com/zcash/lightwalletd/pull/475
